app/reporting/views.py
import os.path as op
import os
import re
import json
import shutil
from datetime import datetime
from lxml import etree
from tqdm import tqdm
import glob
from flask import (
    Blueprint, request, render_template, flash, g, redirect, url_for, Markup)
from sqlalchemy import sql, orm
import xnat
from app import db, app
from .forms import ReportForm, RepairForm, CheckScanTypeForm
from ..views import get_user
from ..models import (
    Project, Subject, ImgSession, Report, Scan, ScanType, ContactInfo)
from ..decorators import requires_login
from ..utils import xnat_id_re
from ..database import empty_sessions
from ..constants import (
    MRI, PATHOLOGIES, REPORTER_ROLE, ADMIN_ROLE,
    DATA_STATUS, FIX_XNAT, PRESENT, NOT_FOUND, UNIMELB_DARIS,
    INVALID_LABEL, CRITICAL, NONURGENT, FIX_OPTIONS,
    FOUND_NO_CLINICAL, NOT_REQUIRED, LOW)
from flask_breadcrumbs import register_breadcrumb, default_breadcrumb_root


mod = Blueprint('reporting', __name__, url_prefix='/reporting')
default_breadcrumb_root(mod, '.reporting')

daris_id_re = re.compile(r'1008\.2\.(\d+)\.(\d+)(?:\.1\.(\d+))?.*')
FM = '{http://www.filemaker.com/fmpxmlresult}'


@mod.before_request
def before_request():
    get_user()


@mod.route('/', methods=['GET'])
@register_breadcrumb(mod, '.', 'Incidental Reporting')
@requires_login()
def index():
    # This should be edited to be a single jumping off page instead of
    # redirects
    return render_template("reporting/index.html",
                           is_reporter=g.user.has_role(REPORTER_ROLE),
                           is_admin=g.user.has_role(ADMIN_ROLE))


@mod.route('/sessions', methods=['GET'])
@register_breadcrumb(mod, '.sessions', 'Sessions to report')
@requires_login(REPORTER_ROLE)
def sessions():
    """
    Display all sessions that still need to be reported.
    """

    # Create query for sessions that still need to be reported
    to_report = (
        ImgSession.require_report()
        .filter_by(data_status=PRESENT)
        # Only show sessions that have exported scans
        .filter(
            Scan.query
            .filter(Scan.session_id == ImgSession.id,
                    Scan.exported)
            .exists())
        # Don't show sessions that have unexported scans or scans of
        # unconfirmed clinicaly relevance
        .filter(~(
            Scan.query
            .join(ScanType)
            .filter(
                Scan.session_id == ImgSession.id,
                sql.or_(~ScanType.confirmed, sql.and_(ScanType.clinical,
                                                      ~Scan.exported)))
            .exists()))
        .order_by(ImgSession.priority.desc(), ImgSession.scan_date)).all()

    if not to_report:
        flash("There are no more sessions to report!", "success")
        return redirect(url_for('reporting.index'))

    return render_template("reporting/sessions.html",
                           page_title="Sessions to Report",
                           sessions=to_report,
                           form_target=url_for('reporting.report'),
                           number_of_rows=len(to_report),
                           include_priority=True)


@mod.route('/report', methods=['GET', 'POST'])
@register_breadcrumb(mod, '.sessions.report', 'Report submission')
@requires_login(REPORTER_ROLE)
def report():
    """
    Enter report
    """

    form = ReportForm(request.form)

    session_id = form.session_id.data

    # Retrieve session from database
    img_session = ImgSession.query.filter_by(
        id=session_id).first()

    if img_session is None:
        raise Exception(
            "Session corresponding to ID {} was not found".format(
                session_id))

    # Dynamically set form fields
    form.scans.choices = [
        (s.id, str(s)) for s in img_session.scans if s.exported]

    if form.selected_only.data != 'true':  # From sessions page
        if form.validate_on_submit():

            # create an report instance not yet stored in the database
            report = Report(
                session_id=session_id,
                reporter_id=g.user.id,
                findings=form.findings.data,
                conclusion=int(form.conclusion.data),
                used_scans=Scan.query.filter(
                    Scan.id.in_(form.scans.data)).all(),
                modality=MRI)

            # Insert the record in our database and commit it
            db.session.add(report)  # pylint: disable=no-member
            db.session.commit()  # pylint: disable=no-member

            # flash will display a message to the user
            flash('Report submitted for {}'.format(session_id), 'success')
            # redirect user to the 'home' method of the user module.
            return redirect(url_for('reporting.sessions'))
        else:
            flash("Some of the submitted values were invalid", "error")
    return render_template("reporting/report.html", session=img_session,
                           form=form, PATHOLOGIES=map(str, PATHOLOGIES),
                           CRITICAL=CRITICAL, NONURGENT=NONURGENT)


@mod.route('/fix-sessions', methods=['GET'])
@register_breadcrumb(mod, '.fix_sessions', 'Sessions to repair')
@requires_login(ADMIN_ROLE)
def fix_sessions():
    # Create query for sessions that need to be fixed
    to_fix = (
        ImgSession.require_report()
        .filter(ImgSession.data_status.in_((
            INVALID_LABEL, NOT_FOUND, UNIMELB_DARIS, FIX_XNAT,
            FOUND_NO_CLINICAL)))
        .order_by(ImgSession.data_status.desc(), ImgSession.scan_date)).all()

    new_missing_scans = (
        ImgSession.require_report()
        .filter_by(data_status=PRESENT)
        .filter(~(
            Scan.query
            .join(ScanType)
            .filter(
                Scan.session_id == ImgSession.id,
                sql.or_(~ScanType.confirmed, ScanType.clinical))
            .exists()))
        .order_by(ImgSession.data_status.desc(), ImgSession.scan_date)).all()

    # Update status of imports that don't have any clinical scans (and all
    # types have been confirmed)
    for img_session in new_missing_scans:
        img_session.data_status = FOUND_NO_CLINICAL

    db.session.commit()  # pylint: disable=no-member

    to_fix = new_missing_scans + to_fix

    if not to_fix:
        flash("There are no more sessions to repair!", "success")
        return redirect(url_for('reporting.index'))

    return render_template("reporting/sessions.html",
                           page_title="Sessions to Repair",
                           sessions=to_fix,
                           form_target=url_for('reporting.repair'),
                           include_status=True,
                           include_subject=True,
                           number_of_rows=len(to_fix),
                           DATA_STATUS=DATA_STATUS)


@mod.route('/repair', methods=['GET', 'POST'])
@register_breadcrumb(mod, '.fix_sessions.repair', 'Repair Session')
@requires_login(ADMIN_ROLE)
def repair():

    form = RepairForm(request.form)

    session_id = form.session_id.data

    # Retrieve session from database
    img_session = ImgSession.query.filter_by(
        id=session_id).first()

    if img_session is None:
        raise Exception(
            "Session corresponding to ID '{}' was not found".format(
                session_id))

    form.old_status.data = img_session.data_status

    if form.selected_only.data != 'true':  # From sessions page
        if form.validate_on_submit():

            old_xnat_id = img_session.xnat_id

            if form.status.data in (PRESENT, FIX_XNAT):
                project_id, xnat_subj_id, xnat_visit_id = xnat_id_re.match(
                    form.xnat_id.data).groups()
                try:
                    project = Project.query.filter_by(id=project_id).one()
                except orm.exc.NoResultFound:
                    with xnat.connect(
                        server=app.config['SOURCE_XNAT_URL'],
                        user=app.config['SOURCE_XNAT_USER'],
                        password=app.config['SOURCE_XNAT_PASSWORD']
                    ) as mbi_xnat:
                        title = mbi_xnat.projects[project_id].description
                    project = Project(project_id, title)
                    db.session.add(project)  # noqa pylint: disable=no-member
                img_session.project = project
                img_session.xnat_subject_id = xnat_subj_id
                img_session.xnat_visit_id = xnat_visit_id

            if form.status.data == PRESENT:
                img_session.check_data_status()
            else:
                img_session.data_status = form.status.data

            # Check to see whether the session is missing clinically relevant
            # scans
            edit_link = ('<a href="javascript:select_session({});">Edit</a>'
                         .format(session_id))

            # flash will display a message to the user
            if img_session.data_status == PRESENT:
                flash(Markup('Repaired {}. {}'.format(session_id, edit_link)),
                      'success')
            elif img_session.data_status == FOUND_NO_CLINICAL:
                flash(Markup((
                    "{} does not contain and clinically relevant scans."
                    " Status set to '{}', change to '{}' if this is "
                    "expected. {}").format(
                        img_session.xnat_id,
                        DATA_STATUS[FOUND_NO_CLINICAL][0],
                        DATA_STATUS[NOT_REQUIRED][0],
                        edit_link)), "warning")
            elif form.status.data != form.old_status.data:
                flash(Markup('Marked {} as "{}". {}'.format(
                    session_id, DATA_STATUS[form.status.data][0], edit_link)),
                      'info')
            elif form.xnat_id.data != old_xnat_id:
                flash(Markup((
                    'Updated XNAT ID of {} but didn\'t update status from '

app/views.py
import re
from datetime import datetime
from flask import (
    request, render_template, flash, g, session, redirect, url_for)
from flask_mail import Message
# from sqlalchemy import sql, orm
from sqlalchemy.exc import IntegrityError
from werkzeug import (  # noqa pylint: disable=no-name-in-module
    check_password_hash, generate_password_hash,
    secure_filename)
from app import db, static_dir, app, signature_images, mail
from .forms import RegisterForm, LoginForm
from .models import User, Role
from .decorators import requires_login
from flask_breadcrumbs import register_breadcrumb


def get_user():
    """
    pull user's profile from the database before every request are treated
    """
    g.user = None
    if 'user_id' in session:
        user = User.query.get(session['user_id'])
        if user is None:
            g.user = None
            session.pop('time_of_last_activity', None)
            return
        logout_msg = None
        try:
            last_activity = session['time_of_last_activity']
        except (KeyError, ValueError):
            logout_msg = (
                "Could not read time of last activity, so logging out '{}'"
                .format(user.name))
        else:
            if datetime.now() > (last_activity +
                                 app.config['AUTO_LOGOUT_PERIOD']):
                logout_msg = ("'{}' has been logged out due to inactivity"
                              .format(user.name))
        if logout_msg is not None:
            session.pop('user_id', None)
            session.pop('time_of_last_activity', None)
            flash(logout_msg, "info")
        else:
            g.user = user
            session['time_of_last_activity'] = datetime.now()


@app.before_request
def before_request():
    get_user()


@app.route('/', methods=['GET'])
@register_breadcrumb(app, '.', 'MBI Subjects DB')
@requires_login()
def index():
    # This should be edited to be a single jumping off page instead of
    # redirects
    return redirect(url_for('reporting.index'))


@app.route('/login/', methods=['GET', 'POST'])
def login():
    """
    Login form
    """
    if g.user is not None and g.user.active:
        return redirect(url_for('reporting.index'))
    form = LoginForm(request.form)
    # make sure data are valid, but doesn't validate password is right
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        # we use werzeug to validate user's password
        if user and check_password_hash(user.password, form.password.data):
            # the session can't be modified as it's signed,
            # it's a safe place to store the user id
            session['user_id'] = user.id
            session['time_of_last_activity'] = datetime.now()
            flash('Welcome {}'.format(user.name), 'success')
            return redirect(url_for('reporting.index'))
        flash('Wrong email or password', 'error')
    return render_template("login.html", form=form)


@app.route('/logout/', methods=['GET', 'POST'])
def logout():
    """
    Logout page
    """
    if g.user is not None:
        user = g.user
        g.user = None
        flash('Logged out {}'.format(user.name), 'info')
    session.pop('user_id', None)
    return redirect(url_for('login'))


@app.route('/register/', methods=['GET', 'POST'])
def register():
    """
    Registration Form
    """
    form = RegisterForm()
    if form.validate_on_submit():
        # Save signature file
        if form.signature.data is not None:
            signature_fname = signature_images.save(form.signature.data,
                                                    name=form.email.data + '.')
        else:
            signature_fname = None
        # create an user instance not yet stored in the database
        user = User(
            title=form.title.data,
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            middle_name=form.last_name.data,
            suffixes=form.suffixes.data,
            email=form.email.data,
            password=generate_password_hash(form.password.data),
            signature=signature_fname,
            roles=[Role.query.get(form.role.data)],
            active=app.config['TEST'])
        # Insert the record in our database and commit it
        db.session.add(user)  # pylint: disable=no-member
        try:
            db.session.commit()  # pylint: disable=no-member
        except IntegrityError as e:
            clash_field = re.match(
                r'.*UNIQUE constraint failed: user.(.*)', e.args[0]).group(1)
            if clash_field == 'email':
                msg = ("The email address '{}' has already been registered"
                       .format(form.email.data))
            elif clash_field == 'name':
                msg = ("The name '{}' has already been registered with the "
                       "email '{}'".format(form.name.data, form.email.data))
            else:
                raise Exception("Unrecognised clash_field, {}"
                                .format(clash_field))
            flash("{}. Please try logging in or contact {} to reset."
                  .format(msg, app.config['ADMIN_EMAIL']), 'error')
        else:
            # flash will display a message to the user
            msg = "Registration successful"
            if not user.active:
                msg += (", please wait to be activated. If urgent contact {}"
                        .format(app.config['ADMIN_EMAIL']))
            flash(msg, 'success')
            msg = Message("New reporting registration: {}"
                          .format(form.email.data),
                          recipients=[app.config['ADMIN_EMAIL']])
            msg.html = render_template('emails/registration.html',
                                       email=form.email.data)
            mail.send(msg)
            return redirect(url_for('login'))
    return render_template("register.html", form=form)

app/templates/reporting/base.html
{% extends "base.html" %}
{% block title %}Incidental Reporting - {% endblock %}
{% block heading %}Incidental Reporting{% endblock %}

app/templates/reporting/check_scan_types.html
{% extends "reporting/base.html" %}
{% from "forms/macros.html" import render_field %}
{% block sub_heading %}Confirm Clinically Relevant Scan Types{% endblock %}
{% block content %}

<form method="POST" action=" {{ url_for('reporting.check_scan_types') }}" class="form">
    {{ form.csrf_token }}
    {{ render_field(form.clinical_scans, class="form-checkbox") }}
    {{ form.viewed_scan_types() }}
    <input type="submit" value="Confirm" class="button green">
    &nbsp;&nbsp;<a href="{{ url_for('reporting.index') }}">Cancel</a>
</form>
{% endblock %}

app/templates/reporting/confirm_scan_types.html
{% extends "reporting/base.html" %}
{% from "forms/macros.html" import render_field %}
{% block sub_heading %}Clinically Relevant Scan Types{% endblock %}
{% block content %}
<h5>Showing {{ num_showing[0] }} of {{ num_showing[1] }} unconfirmed scan types</h5>
<form method="POST" action=" {{ url_for('reporting.confirm_scan_types') }}" class="form">
    {{ form.csrf_token }}
    {{ render_field(form.clinical_scans, class="form-checkbox") }}
    {{ form.viewed_scan_types() }}
    <input type="submit" value="Confirm" class="button green">
    &nbsp;&nbsp;<a href="{{ url_for('reporting.index') }}">Cancel</a>
</form>
{% endblock %}

app/templates/reporting/import.html
{% extends "reporting/base.html" %}
{% block sub_heading %}FileMaker Import{% endblock %}
{% block content %}
Imported {{ num_imported }} sessions from FileMaker, {{ num_prev }} previously imported sessions were skipped<br><br>
{% if malformed %}
<h3>Skipped sessions due to malformed FileMaker export rows</h3>
<table>
    <thead>
        <tr>
            {% for k in malformed[0].keys() %}
            <th>{{ k }}</th>
            {% endfor %}
        </tr>
    </thead>
    {% for row in malformed %}
        <tr>
            {% for v in row.values() %}
            <td>{{ v }}</td>
            {% endfor %}
        </tr>
    {% endfor %}
</table>
{% endif %}<br><br>
{% if no_xnat %}
<h3>Skipped sessions due to missing data on XNAT</h3>
<table>
    <thead>
        <tr>
            {% for k in no_xnat[0].keys() %}
            <th>{{ k }}</th>
            {% endfor %}
        </tr>
    </thead>
    {% for row in no_xnat %}
    <tr>
        {% for v in row.values() %}
        <td>{{ v }}</td>
        {% endfor %}
    </tr>
    {% endfor %}
</table>
{% endif %}
{% if malformed %}
<h3>Skipped sessions as they were not required</h3>
<table>
    <thead>
        <tr>
            {% for k in skipped[0].keys() %}
            <th>{{ k }}</th>
            {% endfor %}
        </tr>
    </thead>
    {% for row in skipped %}
    <tr>
        {% for v in row.values() %}
        <td>{{ v }}</td>
        {% endfor %}
    </tr>
    {% endfor %}
</table>
{% endif %}<br><br>
{% endblock %}

app/templates/reporting/index.html
{% extends "reporting/base.html" %}
{% block content %}
<h4>Links</h4>
<ul>
    {% if is_reporter %}
    <li><a href="{{ url_for('reporting.sessions') }}">Report sessions</a></li>
    {% endif %}
    {% if is_admin %}
    <li><a href="{{ url_for('reporting.fix_sessions') }}">Repair missing/mis-named sessions</a></li>
    <li><a href="{{ url_for('reporting.confirm_scan_types') }}">Confirm clinical relevance of scan types</a></li>
    <li><a href="{{ url_for('reporting.sync_alfred') }}">Sync eligible sessions with Alfred</a></li>
    <li><a href="{{ url_for('reporting.sync_filemaker') }}">Sync data from FileMaker export</a></li>
    {% endif %}
</ul>
{% endblock %}

app/templates/reporting/login.html
{% extends "reporting/base.html" %}
{% block sub_heading %}Login{% endblock %}
{% block content %}
{% from "forms/macros.html" import render_field %}
<form method="POST" action="." class="form">
    {{ form.csrf_token }}
    {{ render_field(form.email, class="form-text") }}
    {{ render_field(form.password, class="form-text") }}
    <input type="submit" value="Login" class="button green">
</form>
<a href="{{ url_for('reporting.register') }}">Register</a>
{% endblock %}

app/templates/reporting/repair.html
{% extends "reporting/base.html" %}
{% from "forms/macros.html" import render_field %}
{% block sub_heading %}Repair Session{% endblock %}
{% block content %}

<script>
    function toggleidbox() {
        if (document.getElementById("status-{{ FIX_OPTIONS.index(PRESENT) }}").checked ||
            document.getElementById("status-{{ FIX_OPTIONS.index(FIX_XNAT) }}").checked) {
            document.getElementById("xnat_id").disabled = '';
        } else {
            document.getElementById("xnat_id").disabled = 'true';
        }
    }
</script>
<label class="form">Session Details</label>
<table class="report">
    <tbody>
        <tr>
            <td class="report-label">Session (Study) ID:</td>
            <td class="report-value">{{ session.id }}</td>
        </tr>
        <tr>
            <td class="report-label">Scan Date:</td>
            <td class="report-value">{{ session.scan_date.strftime('%d/%m/%Y') }}</td>
        </tr>
        <tr>
            <td class="report-label">First Name:</td>
            <td class="report-value">{{ session.subject.first_name }}</td>
        </tr>
        <tr>
            <td class="report-label">Last Name:</td>
            <td class="report-value">{{ session.subject.last_name }}</td>
        </tr>
        <tr>
            <td class="report-label">Subject ID:</td>
            <td class="report-value">{{ session.subject.id }}</td>
        </tr>
        <tr>
            <td class="report-label">DOB:</td>
            <td class="report-value">{{ session.subject.dob.strftime('%d/%m/%Y') }}</td>
        </tr>
        <tr>
            <td class="report-label">XNAT Project:</td>
            <td class="report-value"><a href="{{ xnat_url }}/data/archive/projects/{{xnat_project}}?format=html"
                    target="_blank">{{ xnat_project }}</a></td>
        </tr>
        <tr>
            <td class="report-label">XNAT Subject:</td>
            <td class="report-value"><a
                    href="{{ xnat_url }}/data/archive/projects/{{xnat_project}}/subjects/{{xnat_subject}}?format=html"
                    target="_blank">{{ xnat_subject }}</a></td>
        </tr>
        <tr>
            <td class="report-label">XNAT Session:</td>
            <td class="report-value"><a
                    href="{{ xnat_url }}/data/archive/projects/{{xnat_project}}/experiments/{{session.xnat_id}}?format=html"
                    target="_blank">{{ session.xnat_id }}</a></td>
        </tr>
        <tr>
            <td class="report-label">Current status:</td>
            <td class="report-value">{{ DATA_STATUS[session.data_status][1] }}</td>
        </tr>
    </tbody>
</table>
<form method="POST" action=" {{ url_for('reporting.repair') }}" class="form">
    {{ form.csrf_token }}
    {{ render_field(form.status, class="form-radio",
                    onChange="toggleidbox();") }}
    {{ render_field(form.xnat_id, class="form-input",
                    disabled=(form.status.data not in (PRESENT, FIX_XNAT))) }}
    {{ form.session_id() }}
    <input type="submit" value="Update" class="button green">
    &nbsp;&nbsp;<a href="{{ url_for('reporting.fix_sessions') }}">Cancel</a>
</form>
{% endblock %}

app/templates/reporting/report.html
{% extends "reporting/base.html" %}
{% from "forms/macros.html" import render_field %}
{% block sub_heading %}Report Submission{% endblock %}
{% block content %}

<script>
    function toggletextbox() {
        if (["{{ CRITICAL }}", "{{ NONURGENT }}"].includes(document.getElementById("conclusion").value)) {
            document.getElementById("findings").disabled = '';
        } else {
            document.getElementById("findings").disabled = 'true';
        }
    }
</script>
<label class="form">Session Details</label>
<table class="report">
    <tbody>
        <tr>
            <td class="report-label">Session (Study) ID:</td>
            <td class="report-value"><a href="{{ session.target_xnat_uri }}?format=html" target="_blank">{{ session.id }}</a></td>
        </tr>
        <tr>
            <td class="report-label">Subject ID:</td>
            <td class="report-value">{{ session.subject.id }}</td>
        </tr>
        <tr>
            <td class="report-label">Scan Date:</td>
            <td class="report-value">{{ session.scan_date.strftime('%d/%m/%Y') }}</td>
        </tr>
        <tr>
            <td class="report-label">Priority:</td>
            <td class="report-value">{{ session.priority_str }}</td>
        </tr>
    </tbody>
</table>
<form method="POST" action="{{ url_for('reporting.report') }}" class="form">
    {{ form.csrf_token }}
    {{ render_field(form.conclusion, class="form-select",
                    onChange="toggletextbox();") }}
    {{ render_field(form.findings, class="form-textarea",
                    disabled=(form.conclusion.data not in PATHOLOGIES)) }}
    {{ render_field(form.scans, class="form-checkbox") }}
    {{ form.session_id() }}
    <input type="submit" value="Submit report" class="button green">
    &nbsp;&nbsp;<a href="{{ url_for('reporting.sessions') }}">Cancel</a>
</form>
{% endblock %}

app/templates/reporting/sessions.html
{% extends "reporting/base.html" %}
{% block sub_heading %}{{ page_title }}{% endblock %}
{% block content %}
<script>
    function select_session(session_id) {
        report_form = document.forms['report_form']
        report_form.session_id.value = session_id
        report_form.selected_only.value = true
        report_form.submit();
    }
</script>
<form name="report_form" method="POST" action="{{ form_target }}">
    <input type="hidden" name="session_id">
    {# Used to distinguish from the form submitted on the report/repair page #}
    <input type="hidden" name="selected_only">
</form>
<h5>{{ number_of_rows }} rows</h5>
<table class="sessions">
    <thead>
        <tr>
            <th>Session (Study) ID</th>
            <th>Subject</th>
            <th>Scan Date</th>
            <th>MBI XNAT ID</th>
            {% if include_status %}
            <th>Data Status</th>
            {% endif %}
            {% if include_priority %}
            <th>Priority</th>
            {% endif %}
        </tr>
    </thead>
    <tbody>
{% for img_session in sessions %}
    <tr onclick="{{ 'select_session({});'.format(img_session.id) }}">
        <td class="sessions-id">
            {{ img_session.id }}
        </td>
        <td class="sessions-subject }}">
            {{ img_session.subject.id }}
        </td>
        <td class="sessions-scandate">
            {{ img_session.scan_date.strftime('%d/%m/%Y') }}
        </td>
        <td class="sessions-xnatid">
            {{ img_session.xnat_id }}
        </td>
        {% if include_status %}
        <td class="sessions-status }}">
            {{ DATA_STATUS[img_session.data_status][0] }}
        </td>
        {% endif %}
        {% if include_priority %}
        <td class="sessions-priority-{{ img_session.priority_str.lower() }}">
            {{ img_session.priority_str }}
        </td>
        {% endif %}
    </div>
{% endfor %}
</tbody>
</table>
{% endblock %}